### ISSUE TITLE
AttributeError jugfile.py

### ISSUE THREAD

**Issue by TianyiChang** [luispedro/Coelho2021_GMGCv1#1]
Dear Luis

I was trying to use the jugfile within the folder 'redundant 100' and got the below error message. I wonder if you know what went wrong?

Thanks in advance!

Traceback (most recent call last):
  File "/mnt/scripts/Coelho2021_GMGCv1-main/redundant100/jugfile.py", line 170, in <module>
    barrier()
  File "/home/tchang/.conda/envs/py3/lib/python3.10/site-packages/jug/barrier.py", line 87, in barrier
    if not _can_load_limit_recursion(t, alltasks):
  File "/home/tchang/.conda/envs/py3/lib/python3.10/site-packages/jug/barrier.py", line 46, in _can_load_limit_recursion
    return tsk.can_load()
  File "/home/tchang/.conda/envs/py3/lib/python3.10/site-packages/jug/task.py", line 252, in can_load
    return store.can_load(self.hash())
AttributeError: 'NoneType' object has no attribute 'can_load'

**Comment by luispedro** [comment]
I assume you realized that this is a [Jugfile](https://jug.rtfd.io/) and you need to run `jug execute` (and not `python jugfile.py`)

Can you tell me a bit more about what you are trying to do too? This was the code that we ran for GMGCv1, but we actually have better versions now (we switched some of the executables to C++ instead of Haskell).

This is not code that we are polishing as tool, though, so expect some rough edges.

**Comment by TianyiChang** [comment]
Hi Luis

Thanks a lot for the information! I did mistakenly use python jugfile.py to run it. However, when I used jug execute it returned another error message as shown at the end.

I was trying to follow GMGCv1 to get the 'unigenes' from around 30M predicted ORFs (first to remove 100 redundant ones, and then cluster the rest). I am quite interested in the better versions you mentioned, and was wondering if you could provide me with more information about them?

Thank you again!

  File "/home/tchang/.conda/envs/py3/lib/python3.10/site-packages/jug/utils.py", line 218, in jug_execute
    raise SystemError("Error in system")
SystemError: Error in system

**Comment by luispedro** [comment]
You can check https://github.com/luispedro/redundant100 (depends on https://github.com/luispedro/outsort too)

But do note that this is not code that is made for ease of use and you need to be a bit familiar with how to compile haskell code.
