### ISSUE TITLE
Compilation error in redundant100.

### ISSUE THREAD

**Issue by YilingWang1997** [luispedro/Coelho2021_GMGCv1#2]
I tried to compile the redundant100 and got this error:

Preprocessing executable 'CleanupHeaders' for redundant100-0.0.0...
Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: can't find source for CleanupHeaders
in ./src

From my perspective, is there a file named CleanupHeaders.hs missing in the ./src directory?
Could you please help me solve this problem? Thanks a lot!

**Comment by luispedro** [comment]
Please try this version: https://github.com/luispedro/redundant100 which has some more recent updates (compared to what we were using for GMGCv1)

**Comment by YilingWang1997** [comment]
I'll try. Thank you!
